### PR TITLE
Add Zimbra support (fit conventions a little bit more).

### PR DESCRIPTION
**Pull request by bernimoses**
Changed HTTP request Depth to 1 to follow the conventions and get all collection items.
http://svn.calendarserver.org/repository/calendarserver/CalendarServer/trunk/doc/Extensions/caldav-ctag.txt
This should be updated to use the CTag property!

### CODE REVIEW

**Comment by christian-putzke** [comment]
I've had a look at this and you linked me the specifications for CalDAV. This is a CardDAV plugin which supports also a depth of infinite and does not have a CTag property. Nervertheless if tried a depth of 1 and it seems to have no effect on the results.

If you have experience with CardDAV and Zimbra implementations it would be great if you can help me with my CardDAV PHP Client (https://github.com/graviox/CardDAV-PHP/) to add Zimbra support.

**Comment by bernimoses** [comment]
Oh sry my mistake.
But however setting the depth to 1 works with zimbra and did not affect for example owncloud (its the only server i've tested, too).

Maybee a workarround is to check if there is something with a depth of 0 and if not raise it to 1?

No sry, i have not many experience with implemtations for carddav and zimbra. This was only a try and fail bugfix. ;P

**Comment by christian-putzke** [comment]
Can you provide me a Test account on your Zimbra server so that I can confirm and integrate all the changes? That would be great.

**Comment by bernimoses** [comment]
I've wrote you a mail with all the infos for my Zimbra Server.

**Comment by krambiorix** [comment]
Hi, is there some progress on this?

**Comment by bernimoses** [comment]
Sry i dont know. The account ive made has never been used.

**Pull request closed without merging**
